# Generated by Django 4.2.27 on 2026-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_front',
            field=models.BooleanField(default=False),
        ),
    ]
