# Generated by Django 4.2.27 on 2026-01-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_category_options_blog_featured_front'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured_image',
            new_name='recent_posts',
        ),
    ]
